<?php

use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use Illuminate\Http\Request;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
*/

// Landing page route to load index.blade.php
Route::get('/', function () {
    return view('index');
})->name('home');

// Login page
Route::get('/login', function () {
    return view('auth.login');
})->name('login');

// General dashboard route (for donors or others)
Route::get('/dashboard', function () {
    return view('dashboard'); // if file is resources/views/dashboard.blade.php
    // OR use: return view('dashboard.dashboard'); if you move it inside dashboard folder
})->middleware(['auth', 'verified'])->name('dashboard');

// Admin dashboard route (only auth protected, add role middleware if needed)
Route::get('/admin/dashboard', function () {
    return view('dashboard.adminDash'); // admin dashboard view
})->middleware('auth')->name('admin.dashboard');

// User profile routes protected by auth middleware
Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

// Logout and redirect route
Route::post('/logout-redirect', function (Request $request) {
    Auth::logout();
    $request->session()->invalidate();
    $request->session()->regenerateToken();

    return redirect()->route('home');
})->name('logout.redirect');

// About us page
Route::get('/aboutus', function () {
    return view('about');
})->name('aboutus');

// Include auth routes generated by Laravel Breeze, Fortify, etc.
require __DIR__.'/auth.php';
