<?php

use App\Http\Controllers\ProfileController;
use App\Http\Controllers\CampaignController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use Illuminate\Http\Request;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
*/

// Landing page route to load index.blade.php
Route::get('/', function () {
    return view('index');
})->name('home');

// Login page
Route::get('/login', function () {
    return view('auth.login');
})->name('login');

// Authenticated routes
Route::middleware(['auth', 'verified'])->group(function () {

    // Dashboard shows campaigns list for logged-in user
    Route::get('/dashboard', [CampaignController::class, 'index'])->name('dashboard');

    // Campaigns resource routes except index (since dashboard shows list)
    Route::resource('campaigns', CampaignController::class)->except(['index']);

    // User profile routes
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

// Admin dashboard route (add role middleware if needed)
Route::get('/admin/dashboard', function () {
    return view('dashboard.adminDash'); // admin dashboard view
})->middleware('auth')->name('admin.dashboard');

// Logout and redirect route
Route::post('/logout-redirect', function (Request $request) {
    Auth::logout();
    $request->session()->invalidate();
    $request->session()->regenerateToken();

    return redirect()->route('home');
})->name('logout.redirect');

// About us page
Route::get('/aboutus', function () {
    return view('about');
})->name('aboutus');

// Include auth routes generated by Laravel Breeze, Fortify, etc.
require __DIR__.'/auth.php';

Route::resource('campaigns', CampaignController::class)->except(['index']);

